file=open('records.txt','r')
i=1
line1=int(file.readline())
while i<=line1:
    j=1
    sum=0
    line2=int((file.readline()))
    while j<=4:
        line=int(file.readline())
        print(line,end=' ')
        sum=sum+line
        j=j+1
    k=1
    sum1=0
    line3=int(file.readline())
    while k<=3:
        line=int(file.readline())
        print(line,end=' ')
        sum1=sum1+line
        k=k+1
    l=1
    sum2=0
    line4=int(file.readline())
    while l<=5:
        line=int(file.readline())
        print(line,end=' ')
        sum2=sum2+line
        l=l+1
    m=1
    sum3=0
    line5=int(file.readline())
    while m<=4:
        line=int(file.readline())
        print(line,end=' ')
        sum3=sum3+line
        m=m+1
    while j<5:
        line=int(file.readline())
        print(line,end=' ')
        sum=sum+line
        j=j+1
    j=j+1
    print(f'Average  = {sum}' )